name: Text-Tags
version: 0.03
abstract: parses "folksonomy" space-separated tags (stub module)
author: David Glasser <glasser@bestpractical.com>
license: perl
distribution_type: module
requires:
  Test::More: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.46
